import {reactionSchema,profileSchema,type ActionId,type Context,type EffectId,type Event,type HouseState,type Memory,type Placement,type Profile,type Proposal,type Reaction,type Scope} from './model';
export const matches=(scope:Scope,context:Context)=>(scope.time==='any'||scope.time===context.time)&&(scope.activity==='any'||scope.activity===context.activity);
export const applicableMemories=(s:HouseState,c:Context)=>s.memories.filter(m=>m.status==='active'&&m.profileId===s.profile._id&&matches(m.scope,c));
export function boundaryFor(p:Profile,action:ActionId,c:Context){return p.boundaries.find(b=>b.blockedAction===action&&matches(b,c))}
export const effectForAction:Partial<Record<ActionId,EffectId>>={'sit-quietly':'quiet-chair','share-tea':'tea-for-two','recommend-book':'display-book','offer-plant':'add-plant','leave-note':'keep-note'};
export function greeting(s:HouseState,c:Context):string{const m=applicableMemories(s,c);if(m.some(m=>m.effectId==='quiet-chair'))return "The chair is ready. We can start quietly, like you asked.";if(m.some(m=>m.effectId==='tea-for-two'))return "Two cups today. I kept that little ritual.";if(s.profile.traits.sociability>.65)return "Come in. What story did you bring today?";return c.time==='evening'?"You're welcome to sit. No need to fill the silence.":"Morning. I left a little space by the window."}
export function makeEvent(s:HouseState,objectId:string,action:ActionId,context:Context,detail='',id='event-'+crypto.randomUUID(),createdAt=new Date().toISOString()):Event{const obj=s.objects.find(o=>o._id===objectId);if(!obj||!obj.actions.includes(action))throw Error('That action does not belong to this object.');if(detail.length>250)throw Error('Keep the fictional detail below 250 characters.');return {_id:id,_type:'interactionEvent',profileId:s.profile._id,profileRevision:s.profile._rev||'seed-profile',profileFingerprint:profileFingerprint(s.profile),personaAtTime:{name:s.profile.name,voice:s.profile.voice,traits:structuredClone(s.profile.traits),interests:[...s.profile.interests],boundaries:structuredClone(s.profile.boundaries)},objectId,action,context,detail,createdAt}}
const capText=(s:string,max:number)=>{let out='';for(const ch of s){if(out.length+ch.length>max-1)return out+'…';out+=ch}return out};
export function authoredReaction(s:HouseState,event:Event):Reaction{const boundary=boundaryFor(s.profile,event.action,event.context);const ids=[event._id,s.profile._id];if(boundary)return {reply:`Not during this reading hour. ${boundary.alternative} The chair can stay, though.`,stance:'decline',evidenceIds:ids,proposal:null};const social=s.profile.traits.sociability>.65;const reactions:Record<ActionId,{reply:string;statement?:string}>={
 'sit-quietly':{reply:social?"Quiet company? I can do that. I'll save the story for later.":"Good. I'll move the book a little. You can sit here.",statement:'Our visits should begin quietly.'},
 'start-chat':{reply:social?"I was hoping you would ask. Pick a book and I'll tell you why it stayed.":"One story, then. I found a note in an old book and left it for the next reader."},
 'share-tea':{reply:s.profile.traits.warmth>.65?"Two cups, then. Yours can stay on this side of the table.":"Two cups is a sensible arrangement. Let us try it once.",statement:'Make space for shared tea during visits.'},
 'recommend-book':{reply:`A recommendation about ${event.detail||'a fictional night train'}? I'll put it where I can find it again.`,statement:`Keep a place for this fictional recommendation: ${event.detail||'The Night Train Atlas'}.`},
 'offer-plant':{reply:s.profile.traits.order>.8?"The window corner fits. I would rather keep the desk clear.":"That corner could use something growing. Let's try the window.",statement:'A small plant can live beside the window.'},
 'interrupt-reading':{reply:"The reading hour can wait this time. What did you want to tell me?"},
 'leave-note':{reply:"I'll keep this on the desk for now. You decide whether it belongs on the shelf.",statement:'Keep this fictional note: '+(event.detail||'there is always room for one more page.')}
 };const variants:Partial<Record<ActionId,string[]>>={
 'sit-quietly':[social?"Quiet company? I can do that. I'll save the story for later.":"Good. I'll move the book a little. You can sit here.","You can have the chair by the window. The rain is doing enough talking for both of us.","A page for me, a little space for you. That seems like a reasonable evening."],
 'start-chat':[social?"I was hoping you would ask. Pick a book and I'll tell you why it stayed.":"One story, then. I found a note in an old book and left it for the next reader.","Today's mystery: someone shelved an atlas beside a cookbook. I haven't ruled out a very ambitious dinner.","The room was quiet until a bookmark fell out. It said ‘start here’. Naturally, it was halfway through the book."],
 'share-tea':[reactions['share-tea'].reply,"I set the cups a little apart. Enough room for a book between them, if the conversation wanders.","Careful, it's still warm. There is no schedule for finishing it."],
 'offer-plant':[reactions['offer-plant'].reply,"A plant by the rainy window? It may have a better view than either of us.","The desk is occupied. The window corner, however, has been waiting for a tenant."]};const r={...reactions[event.action]};const choices=variants[event.action];if(choices)r.reply=choices[s.events.filter(e=>e.action===event.action).length%choices.length];const effect=effectForAction[event.action];return {reply:r.reply,stance:'welcome',evidenceIds:ids,proposal:effect&&r.statement?{statement:capText(r.statement,240),scope:{time:'any',activity:'any'},effectId:effect,evidenceIds:ids}:null}}
export function validateReaction(raw:unknown,s:HouseState,event:Event):Reaction{const r=reactionSchema.parse(raw);const allowed=new Set([s.profile._id,event._id,...applicableMemories(s,event.context).map(m=>m._id)]);for(const id of [...r.evidenceIds,...(r.proposal?.evidenceIds||[])])if(!allowed.has(id))throw Error('The response cited evidence that was not supplied.');if(!r.evidenceIds.includes(event._id))throw Error('The response must cite the actual interaction.');const boundary=boundaryFor(s.profile,event.action,event.context);if(boundary&&(r.stance!=='decline'||r.proposal))throw Error('The response tried to bypass a protected ritual.');if(r.stance==='decline'&&r.proposal)throw Error('A declined interaction cannot propose a lasting effect.');if(r.proposal){if(r.proposal.effectId!==effectForAction[event.action])throw Error('The proposed room change is not allowed for this action.');if(!r.proposal.evidenceIds.includes(event._id)||!r.proposal.evidenceIds.includes(s.profile._id))throw Error('A proposal needs both interaction and profile evidence.');}return r}
export function propose(s:HouseState,event:Event,reaction:Reaction,mode:Proposal['generationMode']):HouseState{const r=validateReaction(reaction,s,event);if(s.events.some(e=>e._id===event._id))return s;const proposal:Proposal|null=r.proposal?{_id:'proposal-'+event._id,_type:'memoryProposal',_rev:'local-proposed',profileId:s.profile._id,profileRevision:event.profileRevision,profileFingerprint:event.profileFingerprint,eventId:event._id,...r.proposal,reply:r.reply,generationMode:mode,status:'proposed',createdAt:event.createdAt}:null;return {...s,events:[...s.events,{...event,responseText:r.reply,responseMode:mode}],proposals:proposal?[...s.proposals,proposal]:s.proposals}}
export function approve(s:HouseState,proposalId:string,statement:string,scope:Scope,base:{profileRevision:string;snapshotRevision:string},approvedAt=new Date().toISOString()):HouseState{const p=s.proposals.find(p=>p._id===proposalId);if(!p||p.status!=='proposed')throw Error('This proposal has already been resolved or is missing.');if(base.profileRevision!==(s.profile._rev||'seed-profile')||base.snapshotRevision!==(s.snapshot._rev||'seed-house')||p.profileFingerprint!==profileFingerprint(s.profile))throw Error('The house or personality changed. Review this proposal again.');const event=s.events.find(e=>e._id===p.eventId);if(!event)throw Error('The source interaction is missing.');if(!statement.trim()||statement.length>240)throw Error('A memory needs a concise reviewed statement.');if(!['any','morning','evening'].includes(scope.time)||!['any','reading','social'].includes(scope.activity))throw Error('Invalid memory scope.');validateReaction({reply:p.reply,stance:'welcome',evidenceIds:p.evidenceIds,proposal:{statement,scope,effectId:p.effectId,evidenceIds:p.evidenceIds}},s,event);const memory:Memory={_id:'memory-'+p._id,_type:'approvedMemory',profileId:p.profileId,proposalId:p._id,eventId:p.eventId,statement:statement.trim(),scope,effectId:p.effectId,evidenceIds:p.evidenceIds,status:'active',approvedAt};const next={...s,memories:[...s.memories,memory],proposals:s.proposals.map(x=>x._id===p._id?{...x,status:'approved' as const}:x),snapshot:{...s.snapshot,_rev:'local-'+s.snapshot.edition,edition:s.snapshot.edition+1,memoryIds:[...s.snapshot.memoryIds,memory._id]}};next.snapshot.placements=deriveRoom(next,{time:'evening',activity:'reading'});return next}
export function archiveMemory(s:HouseState,id:string):HouseState{if(!s.memories.some(m=>m._id===id&&m.status==='active'))throw Error('Active memory not found.');const next:HouseState={...s,memories:s.memories.map(m=>m._id===id?{...m,status:'archived'}:m),snapshot:{...s.snapshot,edition:s.snapshot.edition+1,_rev:'local-'+s.snapshot.edition,memoryIds:s.snapshot.memoryIds.filter(x=>x!==id)}};next.snapshot.placements=deriveRoom(next,{time:'evening',activity:'reading'});return next}
export function deriveRoom(s:HouseState,c:Context):Placement[]{profileSchema.parse(s.profile);const t=s.profile.traits,m=applicableMemories(s,c),has=(id:EffectId)=>m.filter(x=>x.effectId===id);const positions:Record<string,[number,number,string,EffectId?]>={
 desk:[47,60,t.order>.7?'A clear desk anchors an orderly routine.':'A desk leaves room for unfinished ideas.','dim-lamp'],
 shelf:[65,57,t.curiosity>.65?'Curiosity gives books the best wall.':'A few familiar books are enough.','display-book'],
 chair:t.privacy>.6?[29,72,'A private corner close to the window.','quiet-chair']:[55,85,'A sociable seat faces the centre of the room.','quiet-chair'],
 plant:[20,61,'An offered gift has a place beside the window.','add-plant'],
 tea:t.warmth>.65?[47,84,'Hospitality leaves room for a second cup.','tea-for-two']:[70,74,'Tea waits at the edge until it is invited in.','tea-for-two'],
 memory:[76,69,'Only reviewed memories become lasting objects.','keep-note']};
 return s.objects.map(o=>{const [x,y,reason,effect]=positions[o.kind];const memories=o.kind==='memory'?s.memories.filter(m=>m.status==='active'&&m.profileId===s.profile._id):effect?has(effect):[];return {_key:o._id,objectId:o._id,x:x+(memories.length&&o.kind==='chair'?5:0)+(t.order<.4?(o.atlasIndex%2?2:-2):0),y:y-(memories.length&&o.kind==='tea'?5:0),width:o.width+(memories.length?1.5:0),reason:memories.length?memories[memories.length-1].statement:reason,sourceIds:memories.length?[...memories].reverse().map(m=>m._id):[s.profile._id],emphasis:memories.length>0,visible:o.kind==='plant'?memories.length>0:o.kind==='memory'?s.memories.some(m=>m.status==='active'):o.kind==='shelf'?t.curiosity>.35||memories.length>0:o.kind==='tea'?t.warmth>.5||memories.length>0:true}})}
export const scopeLabel=(s:Scope)=>`${s.time==='any'?'Any time':s.time} · ${s.activity==='any'?'any visit':s.activity}`;

const ordered=(v:any):any=>Array.isArray(v)?v.map(ordered):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,ordered(v[k])])):v;
export const profileFingerprint=(p:Profile)=>JSON.stringify(ordered({name:p.name,voice:p.voice,traits:p.traits,interests:p.interests,boundaries:p.boundaries}));
export function rejectProposal(s:HouseState,id:string):HouseState{const p=s.proposals.find(p=>p._id===id);if(!p||p.status!=='proposed')throw Error('This proposal is already resolved or missing.');return {...s,proposals:s.proposals.map(p=>p._id===id?{...p,status:'rejected'}:p)}}
