import type {Profile} from './model';
export type StoryChoice={id:string;label:string;reply:string;correct?:boolean};
export type StoryStep={objectId:string;place:string;title:string;clue:string;choices:StoryChoice[]};
export type HouseStory={id:string;title:string;description:string;steps:StoryStep[]};
export const stories:HouseStory[]=[
 {id:'bookmark',title:'The wandering bookmark',description:'Three clues. One book that has lost its place.',steps:[
  {objectId:'object-shelf',place:'Bookshelf',title:'An empty place between pages',clue:'Three books are open: The Night Train Atlas, A Field Guide to Small Wonders, and Letters from the Moon. A blue bookmark lies between them.',choices:[{id:'look',label:'Look for a clue on the desk',reply:'There is a folded scrap under the reading lamp.'}]},
  {objectId:'object-desk',place:'Writing desk',title:'A rather specific invitation',clue:'The scrap reads: “Platform 4. Rain expected. Bring a window seat.” There is no station on the moon. Probably.',choices:[{id:'window',label:'Take the clue to the window chair',reply:'The window seat has been reserved for the investigation.'}]},
  {objectId:'object-chair',place:'The empty chair',title:'Where does the bookmark belong?',clue:'From this chair, the drops on the glass look like passing lights. Which book gets its bookmark back?',choices:[{id:'atlas',label:'The Night Train Atlas',reply:'The blue bookmark settles between two rainy stations.',correct:true},{id:'field',label:'A Field Guide to Small Wonders',reply:'A good place for a leaf. This clue mentions a platform, though.',correct:false},{id:'moon',label:'Letters from the Moon',reply:'An excellent destination. But the ticket was for a train, not a rocket.',correct:false}]}
 ]},
 {id:'tea',title:'A train that goes nowhere',description:'Make a tiny journey from the tea table.',steps:[
  {objectId:'object-tea',place:'Tea for two',title:'The table is a departure board',clue:'Two cups, no timetable. Pick a destination for an imaginary train.',choices:[{id:'sea',label:'The last station by the sea',reply:'Salt on the window. A station clock that has stopped worrying.'},{id:'forest',label:'A forest with no station names',reply:'The train stops when the trees decide it has arrived.'}]},
  {objectId:'object-shelf',place:'Bookshelf',title:'One thing for the journey',clue:'There is room for exactly one thing in the imaginary suitcase.',choices:[{id:'map',label:'A map with an unfinished corner',reply:'We can draw the missing corner when we get there.'},{id:'blank',label:'A book with one blank page',reply:'A sensible precaution. The ending might change.'}]},
  {objectId:'object-chair',place:'The empty chair',title:'The train can wait',clue:'The cups have cooled a little. How should the journey end?',choices:[{id:'stay',label:'Stay here and watch the rain',reply:'The most economical journey: two cups, and the view we already had.'},{id:'return',label:'Promise the train a return trip',reply:'An imaginary return ticket is tucked into the book.'}]}
 ]},
 {id:'letter',title:'One page for tomorrow',description:'Finish an unsigned letter, together.',steps:[
  {objectId:'object-desk',place:'Writing desk',title:'An unfinished first line',clue:'A fictional letter begins: “If you come back tomorrow…” Choose the next line.',choices:[{id:'chair',label:'“…the chair will be by the window.”',reply:'A place can be an invitation without making a speech.'},{id:'question',label:'“…bring a question with no answer.”',reply:'The desk makes room for a question mark.'}]},
  {objectId:'object-chair',place:'The empty chair',title:'A little room in the sentence',clue:'Read it once from the visitor’s chair. What should be left out?',choices:[{id:'clock',label:'Leave out the time',reply:'An invitation with no deadline. That reads better.'},{id:'reason',label:'Leave out the explanation',reply:'The empty chair does a respectable job of explaining itself.'}]},
  {objectId:'object-shelf',place:'Bookshelf',title:'Where should the ending go?',clue:'The last line is still blank. The letter is fictional; its ending is yours to choose.',choices:[{id:'open',label:'Keep one line unfinished',reply:'One page for tomorrow. The book closes without quite ending.'},{id:'home',label:'“There is room for another story.”',reply:'That fits. The letter slips into the book, ready to be found.'}]}
 ]}
];
export type StoryProgress={id:string;step:number;choices:string[];revealed:boolean;feedback:string;complete:boolean;offered:boolean};
export const beginStory=(id:string):StoryProgress=>{if(!stories.some(s=>s.id===id))throw Error('Unknown story');return {id,step:0,choices:[],revealed:false,feedback:'',complete:false,offered:false}};
export function inspectStory(p:StoryProgress,objectId:string):StoryProgress{if(p.complete)return p;const step=stories.find(s=>s.id===p.id)!.steps[p.step];return step.objectId===objectId?{...p,revealed:true}:p}
export function chooseStory(p:StoryProgress,id:string):StoryProgress{if(p.complete||!p.revealed)return p;const story=stories.find(s=>s.id===p.id)!;const choice=story.steps[p.step].choices.find(c=>c.id===id);if(!choice)return p;if(choice.correct===false)return {...p,feedback:choice.reply};const last=p.step===story.steps.length-1;return {...p,step:last?p.step:p.step+1,choices:[...p.choices,id],revealed:last,feedback:choice.reply,complete:last}}
export function storyVoice(profile:Profile,p:StoryProgress):string{const social=profile.traits.sociability>.65,order=profile.traits.order>.85;if(p.id==='bookmark')return social?'Found it! Now we have to invent the journey.':order?'Destination confirmed. Bookmark restored to its proper system.':'A railway atlas. Good. The cookbook was an alarming possibility.';if(p.id==='tea')return social?'Same table, completely different journey. We should try the other route sometime.':order?'No lost luggage. A successful expedition by any reasonable measure.':'We travelled quite a distance for people who never left their chairs.';return social?'I like the empty line. It leaves room for whoever visits next.':order?'A deliberate blank is different from an omission. I will allow it.':'Leave it there. Some sentences are better when they have somewhere to go.'}
export function storySouvenir(p:StoryProgress):string{if(!p.complete)throw Error('Finish the story before preparing a souvenir');if(p.id==='bookmark')return 'We returned the blue bookmark to The Night Train Atlas after following the platform-four clue.';if(p.id==='tea')return `Our imaginary train went to ${p.choices[0]==='sea'?'the sea':'an unnamed forest'}, carrying ${p.choices[1]==='map'?'an unfinished map':'a book with a blank page'}. We ${p.choices[2]==='stay'?'stayed to watch the rain':'kept a return ticket'}.`;return `Our fictional letter offered ${p.choices[0]==='chair'?'a chair by the window':'a question with no answer'}, without ${p.choices[1]==='clock'?'a deadline':'an explanation'}. Its ending ${p.choices[2]==='open'?'keeps one line unfinished':'leaves room for another story'}.`}
