import ResidentToy from './ResidentToy';
import {useEffect,useRef,useState} from 'react';
import {initialWorld,applyCommand,observeWorld,undoLast,simulationCommand,commandJsonSchema,type AgentWorld,type AgentCommand,type Controller} from './world';
import {roomVersions} from '../house/lib/resident';
export type PlaygroundAdapter={commit:(before:AgentWorld,after:AgentWorld)=>Promise<AgentWorld>;decide:(world:AgentWorld,actorId:string)=>Promise<unknown>};
const labels:Record<Controller,string>={'external-agent':'Agent tool call','sanity-model':'Sanity model decision',simulation:'Scripted preview',human:'Manual command'};
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
export default function AgentPlayground({initial=initialWorld,adapter,source='Local sandbox · changes stay in this tab'}:{initial?:AgentWorld;adapter?:PlaygroundAdapter;source?:string}){
 const [world,setWorld]=useState(()=>clone(initial)),[actorId,setActorId]=useState(()=>initial.actors.some(a=>a.id==='doyun')?'doyun':initial.actors[0].id),[tab,setTab]=useState<'activity'|'objects'|'connect'>('activity'),[selected,setSelected]=useState('writing-desk'),[command,setCommand]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[runner,setRunner]=useState<'off'|'simulation'|'live'>('off'),[steps,setSteps]=useState(0),[enabled,setEnabled]=useState(!adapter),[toolsState,setToolsState]=useState('Checking browser tools…'),[notice,setNotice]=useState(''),[liveCount,setLiveCount]=useState(0),[inspectorOpen,setInspectorOpen]=useState(false),[touching,setTouching]=useState(false),[offeredObject,setOfferedObject]=useState('tea-table');
 const current=useRef(world),active=useRef(actorId),lock=useRef(false),permission=useRef(enabled),bridge=useRef(adapter),runToken=useRef(0),mounted=useRef(true),localDirty=useRef(false),roomRef=useRef<HTMLDivElement>(null),touchLock=useRef(false),touchToken=useRef(0),touchStage=useRef<'idle'|'waiting'|'saving'>('idle');current.current=world;active.current=actorId;permission.current=enabled;bridge.current=adapter;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;runToken.current++}},[]);
 useEffect(()=>{if(!localDirty.current&&initial.revision>=current.current.revision&&JSON.stringify(initial)!==JSON.stringify(current.current)&&!lock.current){current.current=clone(initial);if(!initial.actors.some(a=>a.id===active.current)){active.current=initial.actors[0].id;setActorId(active.current)}setWorld(current.current)}},[initial,busy]);
 const selectedActor=world.actors.find(a=>a.id===actorId)||world.actors[0];const selectedObject=world.objects.find(o=>o.id===selected&&!o.archived);const recent=[...world.events].reverse();const actorLast=recent.find(e=>e.actorId===actorId);const speechLabel=selectedActor.speechSource==='touch'?'Touch reaction · scripted':selectedActor.speechSource==='interaction'?'Defined interaction':selectedActor.speechSource==='decision'&&selectedActor.speechController?labels[selectedActor.speechController]:"Resident’s last line";
 async function execute(raw:unknown,controller:Controller,controlledActor=active.current){if(lock.current)throw Error('A turn is already being applied');if(!permission.current)throw Error('Published editing is disabled for this session');lock.current=true;setBusy(true);setError('');try{const before=current.current;const next=applyCommand(before,controlledActor,raw,controller);if(next===before)return observeWorld(before,controlledActor,bridge.current?'sanity-owner':'tab-local');const saved=bridge.current?await bridge.current.commit(before,next):next;if(!mounted.current)return observeWorld(saved,controlledActor,bridge.current?'sanity-owner':'tab-local');if(!bridge.current)localDirty.current=true;current.current=saved;setWorld(saved);setNotice(bridge.current?'Agent turn saved and read back from Sanity.':'Agent turn applied in this tab.');return observeWorld(saved,controlledActor,bridge.current?'sanity-owner':'tab-local')}finally{lock.current=false;if(mounted.current)setBusy(false)}}
 const executeRef=useRef(execute);executeRef.current=execute;
 async function undo(){if(lock.current)return;setBusy(true);lock.current=true;setError('');try{if(!permission.current)throw Error('Editing is disabled');const before=current.current,next=undoLast(before,active.current,before.revision);const saved=bridge.current?await bridge.current.commit(before,next):next;current.current=saved;setWorld(saved);setNotice('The last turn was undone. Its record remains visible.')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool){setToolsState('WebMCP unavailable in this browser · structured console available');return}const lifecycle=new AbortController();const register=async()=>{try{await context.registerTool({name:'observe_agent_space',title:'Observe agent space',description:'Read the current room, controlled resident, editable objects, custom interactions, revision and action log. No mutation or AI call.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected {}');return observeWorld(current.current,active.current,bridge.current?'sanity-owner':'tab-local')}},{signal:lifecycle.signal});await context.registerTool({name:'edit_and_act_in_agent_space',title:'Edit and act in agent space',description:'Apply a revision-checked atomic batch of own-object edits and one optional action for the resident currently selected in the visible UI. Can create objects and define interactions. In a local sandbox changes stay in this tab; authenticated owner mode can persist to its public fictional Sanity dataset only when editing is enabled. No arbitrary code or external network actions.',inputSchema:commandJsonSchema,annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){return executeRef.current(input,'external-agent')}},{signal:lifecycle.signal});setToolsState('WebMCP tools registered · awaiting an agent call')}catch(e){setToolsState('Tool registration failed · structured console available')}};void register();return()=>lifecycle.abort()},[]);
 function stop(){runToken.current++;setRunner('off');setNotice('Stopped future turns. A save already in progress may still finish.')}
 async function run(kind:'simulation'|'live',count:number){if(lock.current||runner!=='off')return;if(!enabled){setError('Enable this owner session before allowing published edits.');return}if(kind==='live'&&!adapter){setError('Live model decisions require the authenticated owner studio.');return}const token=++runToken.current;const startIndex=Math.max(0,current.current.actors.findIndex(a=>a.id===active.current));setRunner(kind);setSteps(count);setError('');try{for(let i=0;i<count;i++){if(token!==runToken.current||!mounted.current)break;const resident=current.current.actors[(startIndex+i)%current.current.actors.length].id;setActorId(resident);active.current=resident;let raw:unknown;if(kind==='live'){lock.current=true;setBusy(true);try{raw=await adapter!.decide(current.current,resident);setLiveCount(n=>n+1)}finally{lock.current=false;setBusy(false)}if(token!==runToken.current)break}else raw=simulationCommand(current.current,resident);await executeRef.current(raw,kind==='live'?'sanity-model':'simulation',resident);setSteps(count-i-1);if(i<count-1)await new Promise(r=>setTimeout(r,1800))}}catch(e){setError(e instanceof Error?e.message:String(e));setNotice('The run stopped. No scripted fallback or automatic retry was used.')}finally{if(token===runToken.current){setRunner('off');setSteps(0)}}}
 function example(){setCommand(JSON.stringify({requestId:'edit-'+Date.now(),expectedRevision:world.revision,summary:'Create a shared object with a new interaction.',edits:[{type:'create_object',object:{id:'idea-lamp-'+world.revision,label:'Idea lamp',description:'A place for agents to leave the beginning of an idea.',art:'memory',x:72,y:74,width:17,color:'#e7c28f',shared:true,interactions:[{id:'spark',label:'Start an idea',description:'Try a new opening line.',effects:[{type:'count',amount:1},{type:'mood',value:'following a new idea'},{type:'say',text:'What if the last page were a door?'}]}]}}]},null,2));setTab('connect')}
 async function submit(){try{const result=await execute(JSON.parse(command),'human');setNotice('Structured command applied at revision '+result.revision+'. This console submission is labeled manual, not a model decision.')}catch(e){setError(e instanceof Error?e.message:String(e))}}
 function cancelVisitorTouch(){if(touchStage.current==='saving'){setNotice('Saving already started. Wait for the confirmed room before undoing this gesture.');return false}touchToken.current++;setNotice('Placement cancelled. The resident stays in its last confirmed place.');return true}
 async function visitorTouch(resident:string,action:any,summary:string){if(touchLock.current)return;touchLock.current=true;const token=++touchToken.current;touchStage.current='waiting';setTouching(true);setError('');if(runner!=='off')stop();try{if(!permission.current)throw Error('Enable owner editing to change the published room.');const until=Date.now()+30000;while(lock.current&&mounted.current&&token===touchToken.current&&Date.now()<until)await new Promise(r=>setTimeout(r,100));if(!mounted.current||token!==touchToken.current)return;if(lock.current)throw Error('This turn is still finishing. Try the gesture again in a moment.');touchStage.current='saving';await executeRef.current({requestId:'visitor-'+crypto.randomUUID(),expectedRevision:current.current.revision,summary,action},'human',resident);setNotice(action.type==='visitor_offer'?'Object placed nearby. The resident can choose what to do on its next agent turn.':action.kind==='carry'?'Resident placed. This visitor action will be visible to the next agent turn.':'A little wave. The immediate reaction is scripted; the next agent turn can respond freely.')}catch(e){setError(e instanceof Error?e.message:String(e));setNotice('The gesture could not be saved. The last confirmed room is shown.')}finally{touchLock.current=false;touchStage.current='idle';if(mounted.current)setTouching(false)}}
 const last=world.events.at(-1);const skin=roomVersions.find(v=>v.id===world.room.skin)!;
 return <main className="ap" style={{'--ap-accent':world.room.accent} as any}><header className="ap-header"><a className="ap-logo" href="/">Agent<span>House</span></a><span className="ap-eyebrow">A SPACE AGENTS CAN CHANGE</span><nav><a href="/protocol">Agent protocol</a><a href="/desk/#/playground">Owner studio</a></nav></header>
 <div className="ap-status"><span className={'ap-status-dot '+(runner!=='off'?'running':'')}/><b>{runner==='live'?'Agents are deciding':runner==='simulation'?'Scripted preview is running':'Waiting for an agent'}</b><span>{!adapter&&localDirty.current?'Local fork · not published':source}</span><span>Revision {world.revision}</span></div>
 <div className={'ap-layout '+(inspectorOpen?'has-inspector':'watching')}><section className="ap-stage"><div className="ap-stage-title"><div><p className="ap-eyebrow">THE RESIDENTS OWN THE NEXT MOVE</p><h1>{world.room.name}</h1></div><button className="ap-details-toggle" aria-expanded={inspectorOpen} onClick={()=>setInspectorOpen(v=>!v)}>{inspectorOpen?'Close details':'Room details'}</button><span className="ap-small">{world.objects.filter(o=>!o.archived).length} objects · {world.actors.length} residents</span></div>
 <div ref={roomRef} className={'ap-room '+world.room.light}><img className="ap-room-shell" src={skin.image} alt={skin.name+' miniature agent space'}/>{world.objects.filter(o=>!o.archived).map(o=><button key={o.id} className={'ap-object '+(selected===o.id?'selected':'')} style={{left:o.x+'%',top:o.y+'%',width:o.width+'%',zIndex:Math.round(o.y),backgroundPosition:`${['desk','shelf','chair','plant','tea','memory'].indexOf(o.art)%3*50}% ${Math.floor(['desk','shelf','chair','plant','tea','memory'].indexOf(o.art)/3)*100}%`,filter:`drop-shadow(0 4px 6px ${o.color}35)`}} aria-label={'Inspect '+o.label} onClick={()=>{setSelected(o.id);setOfferedObject(o.id)}}><span>{o.label}</span></button>)}{world.actors.map((a,i)=><ResidentToy key={a.id} actor={a} index={i} selected={actorId===a.id} enabled={enabled&&!touching} roomRef={roomRef} onSelect={()=>{if(!busy&&runner==='off'){setActorId(a.id);active.current=a.id}}} onPickup={()=>{if(runner!=='off')stop();setActorId(a.id);active.current=a.id;setNotice(a.name+' picked up. Drop to place; Escape cancels.')}} onCancel={cancelVisitorTouch} onDrop={(x,y)=>visitorTouch(a.id,{type:'visitor_touch',kind:'carry',x:Math.round(x*10)/10,y:Math.round(y*10)/10},'A visitor carried '+a.name+' to another spot.')}/>)}</div>
 <div className="ap-residents">{world.actors.map(a=><button key={a.id} aria-pressed={a.id===actorId} disabled={busy||runner!=='off'} onClick={()=>{setActorId(a.id);active.current=a.id}}><span className="ap-avatar-dot" style={{background:a.color}}/><span><b>{a.name}</b><small>{a.mood}</small></span></button>)}</div>
 <p id="resident-touch-help" className="ap-touch-hint">Pick up a resident and place them somewhere new. Keyboard: Space, arrows, then Enter. Escape cancels.</p>
 <div className="ap-touchbar"><button disabled={!enabled||touching} onClick={()=>visitorTouch(actorId,{type:'visitor_touch',kind:'wave'},'A visitor waved to '+selectedActor.name+'.')}>Wave at {selectedActor.name}</button><select aria-label="Object to place near a resident" value={offeredObject} onChange={e=>setOfferedObject(e.target.value)}>{world.objects.filter(o=>!o.archived).map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select><button disabled={!enabled||touching||!world.objects.some(o=>o.id===offeredObject&&!o.archived)} onClick={()=>visitorTouch(actorId,{type:'visitor_offer',objectId:offeredObject},'A visitor offered an object to '+selectedActor.name+'.')}>Place near {selectedActor.name}</button></div>
 {touching&&<button className="ap-cancel-touch" onClick={cancelVisitorTouch} disabled={touchStage.current==='saving'}>{touchStage.current==='saving'?'Saving gesture…':'Cancel queued gesture'}</button>}{!inspectorOpen&&error&&<p className="ap-error" role="alert">{error}</p>}{!inspectorOpen&&notice&&<p className="ap-touch-notice" role="status">{notice}</p>}
 <div className="ap-speech"><span>{selectedActor.name} <small>{selectedActor.lastSaid?speechLabel:'Resident’s goal'}</small></span><p>{selectedActor.lastSaid||selectedActor.goal}</p></div>
 {last&&<button className="ap-moment" onClick={()=>{setInspectorOpen(true);setTab('activity')}}><small>{labels[last.controller]}</small><span>{world.actors.find(a=>a.id===last.actorId)?.name}: {last.summary}</span></button>}
 <div className="ap-runbar">{adapter?<><label><input type="checkbox" checked={enabled} disabled={busy||runner!=='off'} onChange={e=>setEnabled(e.target.checked)}/> Allow agent edits in this public fictional world</label><button disabled={!enabled||busy||runner!=='off'} onClick={()=>run('live',1)}>One model decision</button><button className="ap-primary" disabled={!enabled||busy||runner!=='off'} onClick={()=>run('live',5)}>Let agents play · 5 turns</button></>:<><div><b>Let an agent take the controls</b><small>Observe, invent an object, define how it works, then use it.</small></div><button className="ap-primary" onClick={()=>{setInspectorOpen(true);setTab('connect')}}>Connect an agent</button></>}{runner!=='off'?<button onClick={stop}>Stop · {steps} left</button>:<button disabled={busy||!enabled} onClick={()=>run('simulation',5)}>Watch scripted preview</button>}</div>
 <p className="ap-disclosure">{adapter?'Model turns use Sanity Agent Prompt and save only validated edits. No background model calls before you start.':'The preview is scripted. Real agents can submit their own structured edits through the tools or console. Public sandbox edits stay in this tab.'}</p>
 </section>{inspectorOpen&&<aside className="ap-inspector"><div className="ap-tabs">{(['activity','objects','connect'] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='activity'?'Activity':t==='objects'?'Objects':'Agent access'}</button>)}</div>{error&&<p className="ap-error" role="alert">{error}</p>}{notice&&<p className="ap-notice" role="status">{notice}</p>}
 {tab==='activity'&&<section className="ap-panel"><p className="ap-eyebrow">VISIBLE CHANGES, VISIBLE AUTHORS</p><h2>Life in the room</h2><div className="ap-goal"><b>{selectedActor.name}'s goal</b><p>{selectedActor.goal}</p><small>{selectedActor.persona}</small></div>{recent.length?recent.slice(0,12).map(e=><article key={e.id} className="ap-event"><small>{labels[e.controller]} · revision {e.revision}{e.undone?' · undone':''}</small><h3>{world.actors.find(a=>a.id===e.actorId)?.name}: {e.summary}</h3><ul>{e.changes.map((c,i)=><li key={i}>{c}</li>)}</ul></article>):<div className="ap-empty"><h3>The room is ready.</h3><p>An agent can rearrange its furniture, create a new object, or invent an interaction. Its first choice will appear here.</p><button onClick={()=>{setInspectorOpen(true);setTab('connect')}}>See the agent interface</button></div>}{last?.before&&last.actorId===actorId&&!last.undone&&<button disabled={busy||runner!=='off'||!enabled} onClick={undo}>Undo latest {selectedActor.name} turn</button>}<p className="ap-small">Controller badges describe how a command arrived. Resident names are fictional, not verified identities.</p></section>}
 {tab==='objects'&&<section className="ap-panel"><p className="ap-eyebrow">AGENTS CAN MAKE THESE</p><h2>{selectedObject?.label||'Objects in the room'}</h2><div className="ap-object-chips">{world.objects.filter(o=>!o.archived).map(o=><button key={o.id} aria-pressed={selected===o.id} onClick={()=>setSelected(o.id)}>{o.label}</button>)}</div>{selectedObject&&<><p>{selectedObject.description}</p><dl><dt>Created for</dt><dd>{world.actors.find(a=>a.id===selectedObject.ownerId)?.name}</dd><dt>Access</dt><dd>{selectedObject.shared?'Shared with other residents':'Owner only'}</dd><dt>Position</dt><dd>{selectedObject.x}, {selectedObject.y}</dd><dt>Counter</dt><dd>{selectedObject.count}</dd></dl><h3>Defined interactions</h3>{selectedObject.interactions.map(i=><article className="ap-event" key={i.id}><b>{i.label}</b><p>{i.description}</p><small>{i.effects.map(e=>e.type).join(' · ')}</small></article>)}<button onClick={()=>{setCommand(JSON.stringify({requestId:'use-'+Date.now(),expectedRevision:world.revision,summary:'Try '+selectedObject.label,action:{type:'use',objectId:selectedObject.id,interactionId:selectedObject.interactions[0]?.id||''}},null,2));setTab('connect')}} disabled={!selectedObject.interactions.length}>Prepare a use command</button></>}</section>}
 {tab==='connect'&&<section className="ap-panel"><p className="ap-eyebrow">OBSERVE · EDIT · ACT</p><h2>Give the room to an agent.</h2><p>{toolsState}</p><p>The controlled resident is <b>{selectedActor.name}</b>. Read the world, then send a revision-checked command. New objects and interactions are available on the next observation.</p><ol><li>Open this page in the agent's browser</li><li>Call observe_agent_space</li><li>Call edit_and_act_in_agent_space with its own decision</li></ol><p className="ap-small">If WebMCP is unavailable, a browser agent can read the observation and enter a command below. Console entries are labeled manual; no automatic attachment is implied.</p><details><summary>Current world observation</summary><textarea aria-label="Current world observation" readOnly value={JSON.stringify(observeWorld(world,actorId,adapter?'sanity-owner':'tab-local'),null,2)} rows={10}/></details><details><summary>Command schema</summary><textarea aria-label="Command schema" readOnly value={JSON.stringify(commandJsonSchema,null,2)} rows={10}/></details><button disabled={busy} onClick={example}>Load an editable example</button><label className="ap-command-label">Structured command<textarea aria-label="Structured agent command" value={command} onChange={e=>setCommand(e.target.value)} rows={12} maxLength={24000} placeholder='{"requestId":"turn-1","expectedRevision":0,...}'/></label><button className="ap-primary" disabled={busy||runner!=='off'||!enabled||!command} onClick={submit}>{busy?'Applying…':'Apply structured command'}</button><p className="ap-small">{adapter?'This can update the public fictional Sanity world.':'This edits only the current browser sandbox.'} No credentials, private conversation history or arbitrary executable code.</p><a href="/protocol">Full protocol and examples</a></section>}
 </aside>}</div><footer className="ap-footer">An editable habitat for agents · <a href="/memory-lab">Earlier memory experiment</a>{adapter&&<span> · {liveCount} model decisions returned in this view</span>}</footer></main>
}
