import {useEffect,useRef,useState} from 'react';import type {AgentActor} from './world';
export default function ResidentToy({actor,index,selected,enabled,roomRef,onSelect,onPickup,onDrop,onCancel}:{actor:AgentActor;index:number;selected:boolean;enabled:boolean;roomRef:React.RefObject<HTMLDivElement|null>;onSelect:()=>void;onPickup:()=>void;onDrop:(x:number,y:number)=>Promise<void>;onCancel:()=>boolean}){
 const [held,setHeld]=useState<{x:number;y:number;keyboard:boolean}|null>(null),[pending,setPending]=useState(false);const drag=useRef<{pointer:number;startX:number;startY:number;x:number;y:number;moved:boolean;currentX:number;currentY:number}|null>(null),suppress=useRef(false),button=useRef<HTMLButtonElement>(null),live=useRef({held,pending});live.current={held,pending};const point=held||actor;const pose=held?5:{idle:0,reading:3,tea:4,welcome:5}[actor.pose];
 const clamp=(x:number,y:number)=>({x:Math.max(15,Math.min(85,x)),y:Math.max(55,Math.min(89,y))});
 async function drop(x:number,y:number){setPending(true);try{await onDrop(x,y)}finally{setPending(false);setHeld(null)}}
 function cancel(){if(!drag.current&&!live.current.held&&!live.current.pending)return;if(!onCancel())return;const d=drag.current;drag.current=null;if(d&&button.current?.hasPointerCapture(d.pointer))button.current.releasePointerCapture(d.pointer);setHeld(null);suppress.current=!!d}
 useEffect(()=>{const hide=()=>{if(document.hidden)cancel()};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[]);
 return <button ref={button} className={'ap-agent ap-toy '+(selected?'selected ':'')+(held?'held ':'')+(pending?'pending':'')} style={{left:point.x+'%',top:point.y+'%',zIndex:held?220:Math.round(point.y)+3,backgroundPosition:`${pose%3*50}% ${Math.floor(pose/3)*100}%`,filter:index?'hue-rotate(110deg)':''}} aria-label={`${actor.name}: ${held?'picked up':actor.mood}. Drag to move, or press Space then arrow keys.`} aria-describedby="resident-touch-help" aria-pressed={!!held} aria-disabled={pending} onPointerDown={e=>{if(!enabled||e.button!==0||pending||drag.current)return;e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);drag.current={pointer:e.pointerId,startX:e.clientX,startY:e.clientY,x:actor.x,y:actor.y,moved:false,currentX:actor.x,currentY:actor.y}}} onPointerMove={e=>{const d=drag.current,rect=roomRef.current?.getBoundingClientRect();if(!d||d.pointer!==e.pointerId||!rect?.width||!rect.height)return;if(!d.moved&&Math.hypot(e.clientX-d.startX,e.clientY-d.startY)<6)return;if(!d.moved){d.moved=true;onPickup()}const p=clamp(d.x+(e.clientX-d.startX)/rect.width*100,d.y+(e.clientY-d.startY)/rect.height*100);d.currentX=p.x;d.currentY=p.y;setHeld({...p,keyboard:false})}} onPointerUp={e=>{const d=drag.current;if(!d||d.pointer!==e.pointerId)return;drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const rect=roomRef.current?.getBoundingClientRect();if(d.moved&&rect&&(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)){cancel();return}if(d.moved){suppress.current=true;void drop(d.currentX,d.currentY)}}} onBlur={()=>{if(held?.keyboard||pending)cancel()}} onPointerCancel={cancel} onLostPointerCapture={()=>{if(drag.current)cancel()}} onClick={()=>{if(pending)return;if(suppress.current){suppress.current=false;return}onSelect()}} onKeyDown={e=>{if(e.key==='Escape'&&(held||pending)){e.preventDefault();cancel();return}if(!enabled||pending||e.repeat&&(e.key===' '||e.key==='Enter'))return;if((e.key===' '||e.key==='Enter')&&held?.keyboard){e.preventDefault();void drop(held.x,held.y);return}if(e.key===' '&&!held){e.preventDefault();onPickup();setHeld({x:actor.x,y:actor.y,keyboard:true});return}if(held?.keyboard&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const amount=e.shiftKey?1:3;const p=clamp(held.x+(e.key==='ArrowLeft'?-amount:e.key==='ArrowRight'?amount:0),held.y+(e.key==='ArrowUp'?-amount:e.key==='ArrowDown'?amount:0));setHeld({...p,keyboard:true})}}}><span className="ap-toy-name" style={{borderColor:actor.color}}>{actor.name}</span>{held&&<span className="ap-held-bubble">{pending?'A moment…':actor.id==='atlas'?'An unexpected change of coordinates.':'Oh. We are doing this now.'}</span>}</button>
}
