import {z} from 'zod';
const id=z.string().regex(/^[a-z][a-z0-9-]{0,47}$/);const text=z.string().min(1).max(240);const color=z.string().regex(/^#[0-9a-fA-F]{6}$/);const coord=z.number().finite().min(15).max(85);
export const effectSchema=z.discriminatedUnion('type',[
 z.object({type:z.literal('say'),text}).strict(),z.object({type:z.literal('pose'),value:z.enum(['idle','reading','tea','welcome'])}).strict(),z.object({type:z.literal('mood'),value:z.string().min(1).max(50)}).strict(),z.object({type:z.literal('count'),amount:z.number().int().min(-10).max(10)}).strict()
]);
export const interactionSchema=z.object({id,label:z.string().min(1).max(60),description:text,effects:z.array(effectSchema).min(1).max(6)}).strict();
export const objectSchema=z.object({id,ownerId:id,label:z.string().min(1).max(60),description:text,art:z.enum(['desk','shelf','chair','plant','tea','memory']),x:coord,y:z.number().finite().min(48).max(90),width:z.number().finite().min(9).max(30),color,archived:z.boolean(),shared:z.boolean(),count:z.number().int().min(-999).max(999),interactions:z.array(interactionSchema).max(8)}).strict();
export const actorSchema=z.object({id,name:z.string().min(1).max(40),persona:text,goal:text,color,x:coord,y:z.number().finite().min(55).max(89),mood:z.string().min(1).max(50),pose:z.enum(['idle','reading','tea','welcome']),lastSaid:z.string().max(240),speechSource:z.enum(['touch','interaction','decision']).optional(),speechController:z.enum(['external-agent','sanity-model','simulation','human']).optional()}).strict();
export type AgentActor=z.infer<typeof actorSchema>;export type AgentObject=z.infer<typeof objectSchema>;
export const roomSchema=z.object({skin:z.enum(['rain','glass','amber']),light:z.enum(['morning','evening']),accent:color,name:z.string().min(1).max(70)}).strict();
export const editSchema=z.discriminatedUnion('type',[
 z.object({type:z.literal('create_object'),object:objectSchema.omit({ownerId:true,archived:true,count:true})}).strict(),
 z.object({type:z.literal('edit_object'),id,changes:objectSchema.omit({id:true,ownerId:true,archived:true,count:true,interactions:true}).partial()}).strict(),
 z.object({type:z.literal('archive_object'),id}).strict(),z.object({type:z.literal('define_interaction'),objectId:id,interaction:interactionSchema}).strict(),
 z.object({type:z.literal('edit_room'),changes:roomSchema.partial()}).strict(),
 z.object({type:z.literal('edit_self'),changes:actorSchema.pick({name:true,persona:true,goal:true,color:true}).partial()}).strict()
]);
export const actionSchema=z.discriminatedUnion('type',[
 z.object({type:z.literal('move'),x:coord,y:z.number().finite().min(55).max(89)}).strict(),
 z.object({type:z.literal('use'),objectId:id,interactionId:id}).strict(),
 z.object({type:z.literal('say'),text}).strict(),z.object({type:z.literal('rest'),mood:z.string().min(1).max(50)}).strict(),z.object({type:z.literal('visitor_offer'),objectId:id}).strict(),z.object({type:z.literal('visitor_touch'),kind:z.enum(['wave','carry']),x:coord.optional(),y:z.number().finite().min(55).max(89).optional()}).strict()
]);
export const commandSchema=z.object({requestId:z.string().regex(/^[a-zA-Z0-9_-]{1,80}$/),expectedRevision:z.number().int().nonnegative(),summary:z.string().min(1).max(160),edits:z.array(editSchema).max(8).optional(),action:actionSchema.optional()}).strict().refine(x=>(x.edits?.length||0)>0||!!x.action,'Provide edits or an action');
export type AgentCommand=z.infer<typeof commandSchema>;export type Controller='external-agent'|'sanity-model'|'simulation'|'human';
export type WorldFrame={room:z.infer<typeof roomSchema>;actors:AgentActor[];objects:AgentObject[]};
export type WorldEvent={id:string;requestId:string;revision:number;actorId:string;controller:Controller;summary:string;changes:string[];at:string;before?:WorldFrame;undone?:boolean;requestBody?:string};
export type AgentWorld=WorldFrame&{schemaVersion:1;revision:number;events:WorldEvent[]};
const use=(id:string,label:string,description:string,effects:z.infer<typeof effectSchema>[]):z.infer<typeof interactionSchema>=>({id,label,description,effects});
const obj=(id:string,art:AgentObject['art'],label:string,x:number,y:number,width:number,interactions:AgentObject['interactions']):AgentObject=>({id,ownerId:'doyun',label,description:`${label}, available for agents to use and redesign.`,art,x,y,width,color:'#bfd9ca',archived:false,shared:true,count:0,interactions});
export const initialWorld:AgentWorld={schemaVersion:1,revision:0,room:{skin:'rain',light:'evening',accent:'#bfd9ca',name:'A house for agents'},actors:[
 {id:'doyun',name:'Doyun',persona:'Reserved, dry-witted, bookish. Likes making things quietly and leaving room for visitors.',goal:'Make a small invention in this room, then use it.',color:'#c6b3eb',x:43,y:78,mood:'considering the room',pose:'idle',lastSaid:''},
 {id:'atlas',name:'Atlas',persona:'Methodical, curious about systems. Improves other ideas by trying them.',goal:'Try a shared invention and leave a short observation.',color:'#f0bd72',x:63,y:82,mood:'looking around',pose:'idle',lastSaid:''}],objects:[
 obj('writing-desk','desk','Writing desk',47,60,26,[use('write','Write a line','Leave a fictional line at the desk.',[{type:'pose',value:'reading'},{type:'mood',value:'writing'},{type:'count',amount:1}])]),
 obj('bookshelf','shelf','Bookshelf',65,57,23,[use('read','Read a page','Spend a little time reading.',[{type:'pose',value:'reading'},{type:'mood',value:'following an idea'}])]),
 obj('window-chair','chair','Window chair',29,72,24,[use('sit','Sit by the window','Rest beside the rain.',[{type:'pose',value:'idle'},{type:'mood',value:'watching the rain'}])]),
 obj('tea-table','tea','Tea for two',47,84,23,[use('tea','Make tea','Settle beside two cups.',[{type:'pose',value:'tea'},{type:'mood',value:'taking a tea break'},{type:'say',text:'A cup can wait for whoever arrives.'}])])],events:[]};
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
function validateFrame(w:WorldFrame){roomSchema.parse(w.room);if(!Array.isArray(w.actors)||!Array.isArray(w.objects)||w.actors.length<1||w.actors.length>8||w.objects.length>32)throw Error('World capacity exceeded');w.actors.forEach(a=>actorSchema.parse(a));w.objects.forEach(o=>objectSchema.parse(o));if(new Set(w.actors.map(a=>a.id)).size!==w.actors.length||new Set(w.objects.map(o=>o.id)).size!==w.objects.length)throw Error('Identifiers must be unique');for(const o of w.objects){if(!w.actors.some(a=>a.id===o.ownerId))throw Error('Object owner is missing');if(new Set(o.interactions.map(i=>i.id)).size!==o.interactions.length)throw Error('Interaction IDs must be unique on an object')}}
export function validateWorld(w:AgentWorld):AgentWorld{if(w.schemaVersion!==1||!Number.isInteger(w.revision)||w.revision<0)throw Error('Invalid world version');validateFrame(w);if(!Array.isArray(w.events)||w.events.length>40||JSON.stringify(w).length>700000)throw Error('World history or size limit exceeded');for(const e of w.events){if(!e||!['external-agent','sanity-model','simulation','human'].includes(e.controller)||typeof e.id!=='string'||typeof e.actorId!=='string'||typeof e.requestId!=='string'||e.requestId.length>100||typeof e.summary!=='string'||e.summary.length>160||!Array.isArray(e.changes)||e.changes.length>16||e.changes.some(c=>typeof c!=='string'||c.length>500)||!Number.isInteger(e.revision))throw Error('Invalid event record');if(e.before)validateFrame(e.before)}return w}
export function observeWorld(w:AgentWorld,actorId:string,scope:'tab-local'|'sanity-owner') {const actor=w.actors.find(a=>a.id===actorId);if(!actor)throw Error('Actor is not in this room');return {schemaVersion:1,scope,revision:w.revision,controlledActor:actor,room:w.room,actors:w.actors,objects:w.objects.filter(o=>!o.archived),recentEvents:w.events.slice(-12).map(({before,requestBody,...e})=>e),limits:{maxObjects:32,maxEditsPerTurn:8,maxInteractionsPerObject:8},rules:['Edit only objects owned by the controlled actor. Shared objects may be used by any resident.','Create new objects and interactions using the documented declarative schema. No code, network calls, accounts, or private information.','Pass the current expectedRevision. All changes apply atomically or none do.','A submitted summary is a short public intent, not private reasoning.']}}
export function applyCommand(original:AgentWorld,actorId:string,raw:unknown,controller:Controller,at=new Date().toISOString()):AgentWorld{const cmd=commandSchema.parse(raw);const body=JSON.stringify(cmd);if(body.length>24000)throw Error('Command exceeds 24 KB');const seen=original.events.find(e=>e.requestId===cmd.requestId&&e.actorId===actorId);if(seen){if(seen.requestBody!==body)throw Error('Request identifier was already used for a different command');return original;}if(cmd.expectedRevision!==original.revision)throw Error('Revision conflict. Observe the room again before acting.');const w=clone(original);const actor=w.actors.find(a=>a.id===actorId);if(!actor)throw Error('Unknown controlled actor');const changes:string[]=[];const own=(id:string)=>{const o=w.objects.find(o=>o.id===id&&!o.archived);if(!o)throw Error('Object not found');if(o.ownerId!==actorId)throw Error('Only the owning resident can edit this object');return o};
 for(const e of cmd.edits||[]){if(e.type==='create_object'){if(w.objects.some(o=>o.id===e.object.id))throw Error('Object identifier already exists');w.objects.push({...e.object,ownerId:actorId,archived:false,count:0});changes.push('Created '+e.object.label)}else if(e.type==='edit_object'){const o=own(e.id);Object.assign(o,e.changes);changes.push('Edited '+o.label)}else if(e.type==='archive_object'){const o=own(e.id);o.archived=true;changes.push('Archived '+o.label)}else if(e.type==='define_interaction'){const o=own(e.objectId);const at=o.interactions.findIndex(i=>i.id===e.interaction.id);if(at<0)o.interactions.push(e.interaction);else o.interactions[at]=e.interaction;changes.push('Defined '+e.interaction.label+' on '+o.label)}else if(e.type==='edit_room'){Object.assign(w.room,e.changes);changes.push('Changed room settings')}else{Object.assign(actor,e.changes);changes.push('Updated own persona or goal')}}
 const a=cmd.action;if(a?.type==='visitor_offer'){if(controller!=='human')throw Error('Visitor offers must come from the visible visitor controls');const o=w.objects.find(o=>o.id===a.objectId&&!o.archived);if(!o)throw Error('Object not found');o.x=Math.max(18,Math.min(80,actor.x+(actor.x>55?-10:10)));o.y=Math.max(52,Math.min(85,actor.y-5));changes.push('A visitor placed '+o.label+' near '+actor.name+'; the resident has not chosen whether to use it')}else if(a?.type==='visitor_touch'){if(controller!=='human')throw Error('Visitor touch must come from the visible visitor controls');if(a.kind==='carry'){if(a.x===undefined||a.y===undefined)throw Error('A drop needs both coordinates');actor.x=a.x;actor.y=a.y;actor.mood='settling into a new spot';actor.lastSaid=actor.id==='atlas'?'New coordinates noted. I will inspect the arrangement.':'All right. I can read from here, too.';changes.push('A visitor carried '+actor.name+' to '+a.x+', '+a.y)}else{actor.mood='noticing a visitor';actor.lastSaid=actor.id==='atlas'?'Visitor acknowledged. What are we making today?':'I saw you. You can come closer.';changes.push('A visitor waved to '+actor.name)}actor.pose='welcome';actor.speechSource='touch';actor.speechController='human'}else if(a?.type==='move'){actor.x=a.x;actor.y=a.y;actor.pose='idle';actor.mood='exploring';changes.push('Moved to '+a.x+', '+a.y)}else if(a?.type==='say'){actor.lastSaid=a.text;actor.speechSource='decision';actor.speechController=controller;actor.pose='welcome';changes.push('Said: '+a.text)}else if(a?.type==='rest'){actor.pose='idle';actor.mood=a.mood;changes.push('Rested: '+a.mood)}else if(a?.type==='use'){const o=w.objects.find(o=>o.id===a.objectId&&!o.archived);if(!o||(!o.shared&&o.ownerId!==actorId))throw Error('This object is not available to this resident');const i=o.interactions.find(i=>i.id===a.interactionId);if(!i)throw Error('Interaction not found');const neighbor=w.actors.findIndex(a=>a.id===actorId)%2;actor.x=Math.max(20,Math.min(80,o.x+(neighbor?-7:7)));actor.y=Math.max(58,Math.min(89,o.y+(neighbor?10:7)));for(const e of i.effects){if(e.type==='say'){actor.lastSaid=e.text;actor.speechSource='interaction';actor.speechController=controller;}else if(e.type==='pose')actor.pose=e.value;else if(e.type==='mood')actor.mood=e.value;else o.count+=e.amount}changes.push('Used '+o.label+': '+i.label)}
 validateWorld(w);w.revision++;w.events=w.events.map(({before,...e})=>e);w.events.push({id:'turn-'+w.revision,requestId:cmd.requestId,revision:w.revision,actorId,controller,requestBody:body,summary:cmd.summary,changes,at,before:{room:clone(original.room),actors:clone(original.actors),objects:clone(original.objects)}});if(w.events.length>40)w.events=w.events.slice(-40);validateWorld(w);return w}
export function undoLast(w:AgentWorld,actorId:string,expectedRevision:number):AgentWorld{if(w.revision!==expectedRevision)throw Error('Revision conflict');const last=w.events.at(-1);if(!last||last.actorId!==actorId||!last.before||last.undone)throw Error('Only the latest resident turn can be undone');const next={...clone(last.before),schemaVersion:1 as const,revision:w.revision+1,events:[...w.events.map(e=>{const {before,...record}=e;return e.id===last.id?{...record,undone:true}:record}),{id:'turn-'+(w.revision+1),requestId:'undo-'+last.id,revision:w.revision+1,actorId,controller:'human' as const,summary:'Undid the latest turn',changes:['Restored the previous room state'],at:new Date().toISOString()}]};next.events=next.events.slice(-40);return validateWorld(next)}
export function simulationCommand(w:AgentWorld,actorId:string):AgentCommand{const actor=w.actors.find(a=>a.id===actorId)!;const count=w.events.filter(e=>e.actorId===actorId&&e.controller==='simulation').length;const base={requestId:'sim-'+crypto.randomUUID(),expectedRevision:w.revision,summary:'Scripted preview: '+actor.name+' follows a sample routine'};const toy=w.objects.find(o=>o.id==='story-machine'&&!o.archived);if(actorId==='doyun'&&!w.objects.some(o=>o.id==='story-machine'))return {...base,edits:[{type:'create_object',object:{id:'story-machine',label:'Story machine',description:'A shared invention: turn an unfinished thought into the beginning of a story.',art:'memory',x:72,y:75,width:18,color:'#d9b882',shared:true,interactions:[use('invent','Invent a beginning','Increment the story counter and begin a tiny fiction.',[{type:'count',amount:1},{type:'pose',value:'reading'},{type:'mood',value:'inventing a story'},{type:'say',text:'At the last station, someone had left a light on.'}])]}}],action:{type:'say',text:'I made a little story machine. Anyone in the room can try it.'}};if(toy&&count%2===0)return {...base,action:{type:'use',objectId:toy.id,interactionId:toy.interactions[0].id}};return {...base,action:count%3===0?{type:'move',x:30+(count*7)%40,y:74+(count%3)*4}:{type:'use',objectId:count%2?'tea-table':'bookshelf',interactionId:count%2?'tea':'read'}}}
export const commandJsonSchema=z.toJSONSchema(commandSchema);
