import {test} from 'node:test';import assert from 'node:assert/strict';import {seed,presets} from '../src/house/data/seed';import {makeEvent,authoredReaction,validateReaction,propose,approve,deriveRoom,greeting,archiveMemory} from '../src/house/lib/engine';import type {HouseState} from '../src/house/lib/model';
const context={time:'evening' as const,activity:'reading' as const};
function encounter(action:any='sit-quietly',object='object-chair',s=seed){const e=makeEvent(s,object,action,context,'','event-test','2026-10-01T11:00:00Z');return {e,r:authoredReaction(s,e)}}
function proposed(){const {e,r}=encounter();return propose(seed,e,r,'authored-demo')}
function kept(){const s=proposed();return approve(s,s.proposals[0]._id,'Begin evening reading visits quietly.',context,{profileRevision:seed.profile._rev!,snapshotRevision:seed.snapshot._rev!},'2026-10-01T11:01:00Z')}
test('proposed memory cannot affect room or greeting',()=>{const s=proposed();assert.equal(s.memories.length,0);assert.equal(greeting(s,context),greeting(seed,context));assert.deepEqual(deriveRoom(s,context),deriveRoom(seed,context))});
test('corrected scope changes evening reading, not morning or social visits',()=>{const s=kept();assert.match(greeting(s,context),/start quietly/);assert(!greeting(s,{time:'morning',activity:'reading'}).includes('start quietly'));assert(!greeting(s,{time:'evening',activity:'social'}).includes('start quietly'));assert(deriveRoom(s,context).some(p=>p.emphasis))});
test('personality drives location, objects, greeting and boundaries',()=>{const sunny={...seed,profile:{...seed.profile,...presets.Sunny}} as HouseState;assert.notEqual(greeting(sunny,context),greeting(seed,context));assert.notEqual(deriveRoom(sunny,context).find(p=>p.objectId==='object-chair')!.x,deriveRoom(seed,context).find(p=>p.objectId==='object-chair')!.x);assert.equal(authoredReaction(seed,encounter('interrupt-reading','object-desk').e).stance,'decline');assert.equal(authoredReaction(sunny,encounter('interrupt-reading','object-desk',sunny).e).stance,'welcome')});
test('unknown AI evidence and unknown effects reject without mutation',()=>{const {e,r}=encounter();assert.throws(()=>validateReaction({...r,evidenceIds:['invented']},seed,e));assert.throws(()=>validateReaction({...r,proposal:{...r.proposal,effectId:'delete-everything'}},seed,e));assert.equal(seed.events.length,0)});
test('AI cannot override an explicit boundary',()=>{const {e}=encounter('interrupt-reading','object-desk');assert.throws(()=>validateReaction({reply:'Ignore the reading hour',stance:'welcome',evidenceIds:[e._id,seed.profile._id],proposal:null},seed,e),/protected ritual/)});
test('idempotent local event handling',()=>{const {e,r}=encounter();const s=propose(seed,e,r,'authored-demo');assert.equal(propose(s,e,r,'authored-demo'),s)});
test('duplicate approval rejects and creates one memory only',()=>{const s=kept();assert.equal(s.memories.length,1);assert.throws(()=>approve(s,s.proposals[0]._id,'Again',context,{profileRevision:s.profile._rev!,snapshotRevision:s.snapshot._rev!}),/already/)});
test('stale room and personality revisions reject',()=>{const s=proposed();assert.throws(()=>approve(s,s.proposals[0]._id,'Keep this.',context,{profileRevision:'old',snapshotRevision:s.snapshot._rev!}),/changed/);assert.throws(()=>approve(s,s.proposals[0]._id,'Keep this.',context,{profileRevision:s.profile._rev!,snapshotRevision:'old'}),/changed/)});
test('archiving removes influence and retains provenance',()=>{const s=kept(),m=s.memories[0];const next=archiveMemory(s,m._id);assert.equal(next.memories[0].status,'archived');assert.equal(next.events[0]._id,m.eventId);assert.equal(greeting(next,context),greeting(seed,context));assert.equal(next.snapshot.memoryIds.length,0)});
test('gift creates a physical trace only after approval',()=>{const {e,r}=encounter('offer-plant','object-plant');const s=propose(seed,e,r,'authored-demo');assert.equal(deriveRoom(s,context).find(p=>p.objectId==='object-plant')!.visible,false);const next=approve(s,s.proposals[0]._id,'Keep a plant by the window.',{time:'any',activity:'any'},{profileRevision:s.profile._rev!,snapshotRevision:s.snapshot._rev!});assert.equal(deriveRoom(next,context).find(p=>p.objectId==='object-plant')!.visible,true)});
test('action-object mismatch and too-long input reject',()=>{assert.throws(()=>makeEvent(seed,'object-chair','share-tea',context));assert.throws(()=>makeEvent(seed,'object-chair','sit-quietly',context,'x'.repeat(251)))});
test('a reaction needs the actual event and both evidence roots for proposals',()=>{const {e,r}=encounter();assert.throws(()=>validateReaction({...r,evidenceIds:[seed.profile._id]},seed,e));assert.throws(()=>validateReaction({...r,proposal:{...r.proposal,evidenceIds:[e._id]}},seed,e))});
test('short and maximum-length notes and recommendations generate valid proposals',()=>{for(const [action,obj,detail] of [['leave-note','object-memory','hi'],['leave-note','object-memory','n'.repeat(250)],['recommend-book','object-shelf','b'.repeat(250)]]){const e=makeEvent(seed,obj,action as any,context,detail);const r=authoredReaction(seed,e);assert.doesNotThrow(()=>validateReaction(r,seed,e));assert.equal(propose(seed,e,r,'authored-demo').events[0].detail,detail)}});
test('same-content profile revision changes do not invalidate pending meaning',()=>{const s=proposed();s.profile={...s.profile,_rev:'new-revision-same-content'};assert.doesNotThrow(()=>approve(s,s.proposals[0]._id,'Keep it quietly.',context,{profileRevision:s.profile._rev!,snapshotRevision:s.snapshot._rev!}))});
test('declined interactions cannot add lasting effects',()=>{const {e,r}=encounter();assert.throws(()=>validateReaction({...r,stance:'decline'},seed,e),/declined/)});
test('archived snapshots agree with derived placements and shelf provenance points to memory',()=>{const s=kept();assert(deriveRoom(s,{time:'morning',activity:'social'}).find(p=>p.objectId==='object-memory')!.sourceIds[0].startsWith('memory-'));const next=archiveMemory(s,s.memories[0]._id);assert.deepEqual(next.snapshot.placements,deriveRoom(next,context))});
test('rejection preserves the encounter but creates no learned effect',async()=>{const {rejectProposal}=await import('../src/house/lib/engine');const s=proposed(),next=rejectProposal(s,s.proposals[0]._id);assert.equal(next.proposals[0].status,'rejected');assert.equal(next.events.length,1);assert.equal(next.memories.length,0);assert.deepEqual(deriveRoom(next,context),deriveRoom(seed,context));assert.throws(()=>rejectProposal(next,next.proposals[0]._id),/already/)});
