import {actionIds,effectIds} from './lib/model';
const str=(name:string,description?:string)=>({name,type:'string',description});const ref=(...names:string[])=>({type:'reference',to:names.map(type=>({type}))});const scope={name:'scope',type:'object',fields:[{name:'time',type:'string',options:{list:['any','morning','evening']}},{name:'activity',type:'string',options:{list:['any','reading','social']}}]};
const evidence={name:'evidence',type:'array',of:[ref('agentProfile','interactionEvent','approvedMemory')]};
const placements={name:'placements',type:'array',of:[{type:'object',fields:[{name:'object',...ref('houseObject')},{name:'x',type:'number'},{name:'y',type:'number'},{name:'width',type:'number'},str('reason'),{name:'sources',type:'array',of:[ref('agentProfile','approvedMemory')]},{name:'emphasis',type:'boolean'},{name:'visible',type:'boolean'}]}]};
export const houseSchema:any[]=[
 {name:"agentPlayground",title:"Agent-editable world",type:"document",fields:[str("title"),{name:"revision",type:"number"},{name:"stateJson",type:"text",description:"Validated fictional agent world and bounded event history. No credentials or private user data."}]},
 {name:'agentProfile',title:'Agent personality',type:'document',fields:[str('name'),str('tagline'),{name:'voice',type:'text',description:'Fictional persona voice. Never private user information.'},{name:'traits',type:'object',fields:['privacy','sociability','curiosity','order','warmth'].map(name=>({name,type:'number',validation:(r:any)=>r.required().min(0).max(1)}))},{name:'interests',type:'array',of:[{type:'string'}]},{name:'boundaries',type:'array',of:[{type:'object',fields:[str('label'),{name:'time',type:'string',options:{list:['any','morning','evening']}},{name:'activity',type:'string',options:{list:['any','reading','social']}},{name:'blockedAction',type:'string',options:{list:[...actionIds]}},str('alternative')]}]}]},
 {name:'houseObject',title:'Meaningful object',type:'document',fields:[str('name'),{name:'kind',type:'string',options:{list:['desk','shelf','chair','plant','tea','memory']}},{name:'atlasIndex',type:'number'},str('description'),{name:'actions',type:'array',of:[{type:'string',options:{list:[...actionIds]}}]},{name:'width',type:'number'}]},
 {name:'interactionEvent',title:'Observed encounter',type:'document',fields:[{name:'profile',...ref('agentProfile')},str('profileRevision'),str('profileFingerprint'),{name:'personaAtTime',type:'object',fields:[str('name'),{name:'voice',type:'text'},{name:'traits',type:'object',fields:['privacy','sociability','curiosity','order','warmth'].map(name=>({name,type:'number'}))},{name:'interests',type:'array',of:[{type:'string'}]},{name:'boundaries',type:'array',of:[{type:'object',fields:[str('label'),str('time'),str('activity'),str('blockedAction'),str('alternative')]}]}]}, {name:'responseText',type:'text'},str('responseMode'),evidence,{name:'object',...ref('houseObject')},{name:'action',type:'string',options:{list:[...actionIds]}},{...scope,name:'context'},str('detail','Invented demo details only.'),{name:'createdAt',type:'datetime'}]},
 {name:'memoryProposal',title:'Proposed meaning',type:'document',fields:[{name:'profile',...ref('agentProfile')},str('profileRevision'),str('profileFingerprint'),{name:'event',...ref('interactionEvent')},{name:'statement',type:'text'},scope,{name:'effectId',type:'string',options:{list:[...effectIds]}},evidence,{name:'reply',type:'text'},{name:'generationMode',type:'string',options:{list:['authored-demo','sanity-agent']}},{name:'status',type:'string',options:{list:['proposed','approved','rejected']}},{name:'createdAt',type:'datetime'},{name:'reviewedStatement',type:'text'},{...scope,name:'reviewedScope'},{name:'approvedAt',type:'datetime'}]},
 {name:'approvedMemory',title:'Reviewed memory',type:'document',fields:[{name:'profile',...ref('agentProfile')},{name:'proposal',...ref('memoryProposal')},{name:'event',...ref('interactionEvent')},{name:'statement',type:'text'},scope,{name:'effectId',type:'string',options:{list:[...effectIds]}},evidence,{name:'status',type:'string',options:{list:['active','archived']}},{name:'approvedAt',type:'datetime'}]},
 {name:'houseSnapshot',title:'Published home',type:'document',fields:[{name:'profile',...ref('agentProfile')},str('profileFingerprint','Canonical personality content used to derive this room.'),{name:'edition',type:'number'},placements,{name:'memories',type:'array',of:[ref('approvedMemory')]}]}
];
