import {useEffect,useRef} from 'react';
import type {Profile} from '../lib/model';
import {stories,storyVoice,storySouvenir,type StoryProgress} from '../lib/stories';
export default function StoryPanel({profile,progress,finished,onStart,onInspect,onChoose,onClose,onOffer}:{profile:Profile;progress:StoryProgress|null;finished:string[];onStart:(id:string)=>void;onInspect:(id:string)=>void;onChoose:(id:string)=>void;onClose:()=>void;onOffer:()=>void}){
 const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus({preventScroll:true})},[progress?.id,progress?.step,progress?.revealed,progress?.complete]);
 if(!progress)return <div className="ah-panel ah-story-panel"><p className="ah-eyebrow">A LITTLE TIME TOGETHER</p><h2 ref={heading} tabIndex={-1}>Stay for a story.</h2><p>Follow clues around the room and choose an ending. Nothing becomes a memory unless you decide to keep it.</p>{stories.map((s,i)=><button className="ah-story-card" key={s.id} onClick={()=>onStart(s.id)}><span className="ah-story-number">0{i+1}</span><span><b>{s.title}</b><small>{s.description}</small><em>{finished.includes(s.id)?'Played · try another ending':'Three small moments'}</em></span></button>)}<p className="ah-footnote">Authored mini-stories. Progress stays in this tab. No AI calls.</p></div>;
 const story=stories.find(s=>s.id===progress.id)!;const step=story.steps[progress.step];
 return <div className="ah-panel ah-story-panel"><p className="ah-eyebrow">{progress.complete?'AN ENDING, FOR NOW':`MOMENT ${progress.step+1} / ${story.steps.length}`}</p><h2 ref={heading} tabIndex={-1}>{story.title}</h2><div className="ah-story-progress" aria-label={`${progress.complete?3:progress.step} of 3 moments complete`}>{story.steps.map((_,i)=><span key={i} className={i<progress.step||progress.complete?'done':i===progress.step?'current':''}/>)}</div>{progress.feedback&&<p className="ah-story-feedback" role="status">{progress.feedback}</p>}{progress.complete?<><blockquote className="ah-story-voice">{storyVoice(profile,progress)}</blockquote><small className="ah-footnote">{profile.name} · authored character voice</small><div className="ah-story-souvenir"><b>A note from this visit</b><p>{storySouvenir(progress)}</p><button className="ah-primary" disabled={progress.offered} onClick={onOffer}>{progress.offered?'Note prepared':'Prepare a souvenir note'}</button><small>Draft only. Offer it at the desk, then review any proposed memory.</small></div><button className="ah-text-button" onClick={onClose}>Choose another story</button></>:<><h3>{step.title}</h3>{progress.revealed?<><p className="ah-story-clue">{step.clue}</p><div className="ah-story-choices">{step.choices.map(c=><button key={c.id} onClick={()=>onChoose(c.id)}>{c.label}</button>)}</div></>:<><p>Look at the {step.place.toLowerCase()} to discover the next part. You can select it in the room.</p><button className="ah-primary" onClick={()=>onInspect(step.objectId)}>Inspect {step.place}</button></>}<button className="ah-text-button" onClick={onClose}>Leave this story</button></>}<p className="ah-footnote">Authored mini-story · no AI request or automatic learning</p></div>
}
